name: mailsender
version: '${project.version}'
main: me.hans.mailsender.Mailsender
api-version: '1.20'
commands:
  mail:
    description: "This is a command for sent email to inbox"
    usage: "/<command> target subject text"
    aliases: [ sentmail ]
    permission: mail.command.sentmail
    permission-message: "You do not have permission to use this command"
